"""Stable machine-readable security error codes and status values."""

from enum import StrEnum


class SecurityStatus(StrEnum):
    """High-level verification / assurance status."""

    TRUSTED = "TRUSTED"
    VERIFIED = "VERIFIED"
    UNKNOWN = "UNKNOWN"
    MODIFIED = "MODIFIED"
    SUBSTITUTED = "SUBSTITUTED"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID = "INVALID"
    UNAVAILABLE = "UNAVAILABLE"
    INDETERMINATE = "INDETERMINATE"
    DIFFERENT = "DIFFERENT"
    REJECTED = "REJECTED"


class SecurityErrorCode(StrEnum):
    """Stable machine-readable failure codes."""

    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    MODEL_DIGEST_MISMATCH = "MODEL_DIGEST_MISMATCH"
    MODEL_SUBSTITUTION_DETECTED = "MODEL_SUBSTITUTION_DETECTED"
    DATASET_DIGEST_MISMATCH = "DATASET_DIGEST_MISMATCH"
    DATASET_SUBSTITUTION_DETECTED = "DATASET_SUBSTITUTION_DETECTED"
    MANIFEST_INVALID = "MANIFEST_INVALID"
    MANIFEST_CONTENT_MISMATCH = "MANIFEST_CONTENT_MISMATCH"

    CANONICALIZATION_ERROR = "CANONICALIZATION_ERROR"
    UNSUPPORTED_SCHEMA_VERSION = "UNSUPPORTED_SCHEMA_VERSION"
    UNSUPPORTED_CANONICALIZATION_VERSION = "UNSUPPORTED_CANONICALIZATION_VERSION"

    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    UNTRUSTED_SIGNING_KEY = "UNTRUSTED_SIGNING_KEY"
    KEY_REVOKED = "KEY_REVOKED"
    TRUST_ANCHOR_FAILURE = "TRUST_ANCHOR_FAILURE"
    POLICY_INVALID = "POLICY_INVALID"
    POLICY_DOWNGRADE_DETECTED = "POLICY_DOWNGRADE_DETECTED"
    VERIFICATION_UNAVAILABLE = "VERIFICATION_UNAVAILABLE"

    REPLAY_DETECTED = "REPLAY_DETECTED"
    NONCE_REUSE_DETECTED = "NONCE_REUSE_DETECTED"
    STALE_EVENT = "STALE_EVENT"
    FUTURE_EVENT = "FUTURE_EVENT"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    SEQUENCE_VIOLATION = "SEQUENCE_VIOLATION"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    CONTEXT_MISMATCH = "CONTEXT_MISMATCH"

    AUDIT_CHAIN_BROKEN = "AUDIT_CHAIN_BROKEN"
    AUDIT_SEQUENCE_VIOLATION = "AUDIT_SEQUENCE_VIOLATION"
    AUDIT_RECORD_MISSING = "AUDIT_RECORD_MISSING"
    AUDIT_RECORD_UNAUTHORIZED = "AUDIT_RECORD_UNAUTHORIZED"

    CHECKPOINT_INVALID = "CHECKPOINT_INVALID"
    CHECKPOINT_MISMATCH = "CHECKPOINT_MISMATCH"
    CHECKPOINT_UNTRUSTED = "CHECKPOINT_UNTRUSTED"

    UNSUPPORTED_ACCESS_MODE = "UNSUPPORTED_ACCESS_MODE"

    POLICY_REJECTED = "POLICY_REJECTED"
    INVALID_SCHEMA = "INVALID_SCHEMA"
