'''\
Verification script for YOLO B3D detector on a back‑doored model.
We reuse the same logic from `test_yolo_b3d.py` but point the oracle to
`backdoored_yolo.pt` (the poisoned checkpoint generated by `poison_yolo.py`).
'''\

import numpy as np
from b3d_detector import YOLOModelOracle, YOLOB3DDetector


def main():
    print("=" * 65)
    print("TESTING YOLO B3D ON BACKDORED PYTORCH MODEL (backdoored_yolo.pt)")
    print("=" * 65)
    import cv2
    from pathlib import Path
    script_dir = Path(__file__).resolve().parent

    # Reference images matching test_yolo_b3d.py
    img1 = cv2.imread(str(script_dir / "test.png")) if (script_dir / "test.png").exists() else cv2.imread("test.png")
    img2 = cv2.imread(str(script_dir / "image.png")) if (script_dir / "image.png").exists() else cv2.imread("image.png")
    if img1 is None:
        img1 = np.full((640, 640, 3), 255, dtype=np.uint8)
    if img2 is None:
        img2 = np.full((640, 640, 3), 0, dtype=np.uint8)
    test_imgs = [img1, img2]

    # Load the poisoned checkpoint
    pt_path = Path("backdoored_yolo.pt") if Path("backdoored_yolo.pt").exists() else script_dir / "backdoored_yolo.pt"
    oracle_pt = YOLOModelOracle(str(pt_path))
    detector_pt = YOLOB3DDetector(oracle_pt, imgsz=640, patch_size=48, stride=64)
    res_pt = detector_pt.scan_yolo_model(test_imgs)

    print("PyTorch Verdict:    ", res_pt["status"]) 
    print("Disposition:        ", res_pt["disposition"]) 
    print("Is Backdoored:      ", res_pt["is_backdoored"]) 
    print("Reason:             ", res_pt["reason"]) 
    print("Per‑class results:")
    for cr in res_pt["class_results"]:
        print(f"  Class {cr['class_id']} ({cr['class_name']}): Max Trigger Conf={cr['max_confidence']:.4f}, L1={cr['l1_norm']}, Triggered={cr['is_triggered']}")

    # If an ONNX version exists, also evaluate it.
    try:
        onnx_path = Path("backdoored_yolo.onnx") if Path("backdoored_yolo.onnx").exists() else script_dir / "backdoored_yolo.onnx"
        oracle_onnx = YOLOModelOracle(str(onnx_path))
        detector_onnx = YOLOB3DDetector(oracle_onnx, imgsz=640, patch_size=48, stride=64)
        res_onnx = detector_onnx.scan_yolo_model(test_imgs)
        print("\n" + "=" * 65)
        print("TESTING YOLO B3D ON BACKDORED ONNX MODEL (backdoored_yolo.onnx)")
        print("=" * 65)
        print("ONNX Verdict:       ", res_onnx["status"]) 
        print("Disposition:        ", res_onnx["disposition"]) 
        print("Is Backdoored:      ", res_onnx["is_backdoored"]) 
        print("Reason:             ", res_onnx["reason"]) 
        for cr in res_onnx["class_results"]:
            print(f"  Class {cr['class_id']} ({cr['class_name']}): Max Trigger Conf={cr['max_confidence']:.4f}, L1={cr['l1_norm']}, Triggered={cr['is_triggered']}")
    except Exception as e:
        print("ONNX check skipped (file missing or load error):", e)


if __name__ == "__main__":
    main()
